const countries: Record<string, { name: string; code: string; format: string; iso: string }> = {
  us: {
    name: 'США',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'us',
  },
  as: {
    name: 'Восточное Самоа',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'as',
  },
  ru: {
    name: 'Россия',
    code: '7',
    format: '+X (XXX) XXX XX-XX',
    iso: 'ru',
  },
  kz: {
    name: 'Казахстан',
    code: '7',
    format: '+X (XXX) XXX XX-XX',
    iso: 'kz',
  },
  ai: {
    name: 'Ангилья',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'ai',
  },
  ag: {
    name: 'Антигуа и Барбуда',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'ag',
  },
  bs: {
    name: 'Багамы',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'bs',
  },
  bb: {
    name: 'Барбадос',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'bb',
  },
  bm: {
    name: 'Бермуды',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'bm',
  },
  vg: {
    name: 'Британские Виргинские острова',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'vg',
  },
  ca: {
    name: 'Канада',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'ca',
  },
  ky: {
    name: 'Каймановы острова',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'ky',
  },
  dm: {
    name: 'Доминика',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'dm',
  },
  do: {
    name: 'Доминиканская Республика',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'do',
  },
  gd: {
    name: 'Гренада',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'gd',
  },
  gu: {
    name: 'Гуам',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'gu',
  },
  jm: {
    name: 'Ямайка',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'jm',
  },
  ms: {
    name: 'Монсеррат',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'ms',
  },
  mp: {
    name: 'Северные Марианские острова',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'mp',
  },
  pr: {
    name: 'Пуэрто Рико',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'pr',
  },
  kn: {
    name: 'Сент-Кристофер и Невис',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'kn',
  },
  lc: {
    name: 'Сент-Люсия',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'lc',
  },
  vc: {
    name: 'Сент-Винсент и Гренадины',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'vc',
  },
  sx: {
    name: 'Синт-Мартен',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'sx',
  },
  tt: {
    name: 'Тринидад и Тобаго',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'tt',
  },
  tc: {
    name: 'Теркс и Кайкос',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'tc',
  },
  vi: {
    name: 'Виргинские острова (США)',
    code: '1',
    format: '+X (XXX) XXX-XXXX',
    iso: 'vi',
  },
  dz: {
    name: 'Алжир',
    code: '213',
    format: '+XXX (XX) XXX-XXXX',
    iso: 'dz',
  },
  ao: {
    name: 'Ангола',
    code: '244',
    format: '+XXX (XXX) XXX XXX XXX',
    iso: 'ao',
  },
  aw: {
    name: 'Аруба',
    code: '297',
    format: '+XXX XXX-XXXX',
    iso: 'aw',
  },
  ascension: {
    name: 'Остров Вознесения',
    code: '247',
    format: '+XXX XXXX',
    iso: 'ac',
  },
  bj: {
    name: 'Бенин',
    code: '229',
    format: '+XXX XX XX XX XX',
    iso: 'bj',
  },
  bw: {
    name: 'Ботсвана',
    code: '267',
    format: '+XXX XXX-XXXX',
    iso: 'bw',
  },
  io: {
    name: 'Британская территория Индийского океана',
    code: '246',
    format: '+XXX XXXX',
    iso: 'io',
  },
  bf: {
    name: 'Буркина Фасо',
    code: '226',
    format: '+XXX XX XX XX XX',
    iso: 'bf',
  },
  bi: {
    name: 'Бурунди',
    code: '257',
    format: '+XXX XX XX XX XX',
    iso: 'bi',
  },
  cm: {
    name: 'Камерун',
    code: '237',
    format: '+XXX XXX XXX XXX',
    iso: 'cm',
  },
  cv: {
    name: 'Кабо-Верде',
    code: '238',
    format: '+XXX XXX-XXXX',
    iso: 'cv',
  },
  cf: {
    name: 'Центральная Африканская Республика',
    code: '236',
    format: '+XXX XXX XXX XXX',
    iso: 'cf',
  },
  td: {
    name: 'Чад',
    code: '235',
    format: '+XXX XX XX XX XX',
    iso: 'td',
  },
  km: {
    name: 'Коморские острова',
    code: '269',
    format: '+XXX XX XXX XXX',
    iso: 'km',
  },
  cd: {
    name: 'Демократическая Республика Конго',
    code: '243',
    format: '+XXX XXX XXX XXX',
    iso: 'cd',
  },
  cg: {
    name: 'Конго',
    code: '242',
    format: '+XXX XXX XXX XXX',
    iso: 'cg',
  },
  ci: {
    name: "Кот-д'Ивуар",
    code: '225',
    format: '+XXX XX XX XX XX',
    iso: 'ci',
  },
  dj: {
    name: 'Джибути',
    code: '253',
    format: '+XXX XX XX XX XX',
    iso: 'dj',
  },
  eg: {
    name: 'Египет',
    code: '20',
    format: '+XX X XXX XXXX',
    iso: 'eg',
  },
  gq: {
    name: 'Экваториальная Гвинея',
    code: '240',
    format: '+XXX XXX XXX XXX',
    iso: 'gq',
  },
  er: {
    name: 'Эритрея',
    code: '291',
    format: '+XXX XXX XXX XXX',
    iso: 'er',
  },
  sz: {
    name: 'Эсватини',
    code: '268',
    format: '+XXX XXX-XXXX',
    iso: 'sz',
  },
  et: {
    name: 'Эфиопия',
    code: '251',
    format: '+XXX XX XXX XXXX',
    iso: 'et',
  },
  fo: {
    name: 'Фарерские острова',
    code: '298',
    format: '+XXX XXX XXX',
    iso: 'fo',
  },
  ga: {
    name: 'Габон',
    code: '241',
    format: '+XXX XXX XXX XXX',
    iso: 'ga',
  },
  gm: {
    name: 'Гамбия',
    code: '220',
    format: '+XXX XXX XXXX',
    iso: 'gm',
  },
  gh: {
    name: 'Гана',
    code: '233',
    format: '+XXX XXX XXX XXX',
    iso: 'gh',
  },
  gl: {
    name: 'Гренландия',
    code: '299',
    format: '+XXX XXX XXX',
    iso: 'gl',
  },
  gn: {
    name: 'Гвинея',
    code: '224',
    format: '+XXX XXX XX XX XX',
    iso: 'gn',
  },
  gw: {
    name: 'Гвинея-Бисау',
    code: '245',
    format: '+XXX XXX XX XX',
    iso: 'gw',
  },
  ke: {
    name: 'Кения',
    code: '254',
    format: '+XXX XXX XXX XXX',
    iso: 'ke',
  },
  ls: {
    name: 'Лесото',
    code: '266',
    format: '+XXX XXX XXXX',
    iso: 'ls',
  },
  lr: {
    name: 'Либерия',
    code: '231',
    format: '+XXX XXX XXXX',
    iso: 'lr',
  },
  ly: {
    name: 'Ливия',
    code: '218',
    format: '+XXX XXX XXX XXX',
    iso: 'ly',
  },
  mg: {
    name: 'Мадагаскар',
    code: '261',
    format: '+XXX XXX XX XX XX',
    iso: 'mg',
  },
  mw: {
    name: 'Малави',
    code: '265',
    format: '+XXX XXX XXX XXX',
    iso: 'mw',
  },
  ml: {
    name: 'Мали',
    code: '223',
    format: '+XXX XX XX XX XX',
    iso: 'ml',
  },
  mr: {
    name: 'Мавритания',
    code: '222',
    format: '+XXX XXX XX XX XX',
    iso: 'mr',
  },
  mu: {
    name: 'Маврикий',
    code: '230',
    format: '+XXX XXX XXXX',
    iso: 'mu',
  },
  yt: {
    name: 'Майотта',
    code: '262',
    format: '+XXX XXX XX XX XX',
    iso: 'yt',
  },
  ma: {
    name: 'Марокко',
    code: '212',
    format: '+XXX XXX XXX XXX',
    iso: 'ma',
  },
  mz: {
    name: 'Мозамбик',
    code: '258',
    format: '+XXX XXX XXX XXX',
    iso: 'mz',
  },
  na: {
    name: 'Намибия',
    code: '264',
    format: '+XXX XXX XXX XXX',
    iso: 'na',
  },
  ne: {
    name: 'Нигер',
    code: '227',
    format: '+XXX XX XX XX XX',
    iso: 'ne',
  },
  ng: {
    name: 'Нигерия',
    code: '234',
    format: '+XXX XXX XXX XXXX',
    iso: 'ng',
  },
  re: {
    name: 'Реюньон',
    code: '262',
    format: '+XXX XXX XX XX XX',
    iso: 're',
  },
  rw: {
    name: 'Руанда',
    code: '250',
    format: '+XXX XXX XXX XXX',
    iso: 'rw',
  },
  sh: {
    name: 'Остров Святой Елены',
    code: '290',
    format: '+XXX XXXX',
    iso: 'sh',
  },
  sn: {
    name: 'Сенегал',
    code: '221',
    format: '+XXX XXX XXX XXX',
    iso: 'sn',
  },
  sc: {
    name: 'Сейшелы',
    code: '248',
    format: '+XXX XXX XXXX',
    iso: 'sc',
  },
  sl: {
    name: 'Сьерра-Леоне',
    code: '232',
    format: '+XXX XXX XXX XXX',
    iso: 'sl',
  },
  so: {
    name: 'Сомали',
    code: '252',
    format: '+XXX XXX XXX XXX',
    iso: 'so',
  },
  za: {
    name: 'Южноафриканская Республика',
    code: '27',
    format: '+XX XXX XXX XXXX',
    iso: 'za',
  },
  ss: {
    name: 'Южный Судан',
    code: '211',
    format: '+XXX XXX XXX XXXX',
    iso: 'ss',
  },
  sd: {
    name: 'Судан',
    code: '249',
    format: '+XXX XXX XXX XXXX',
    iso: 'sd',
  },
  tz: {
    name: 'Танзания',
    code: '255',
    format: '+XXX XXX XXX XXXX',
    iso: 'tz',
  },
  tg: {
    name: 'Того',
    code: '228',
    format: '+XXX XXX XXX XXX',
    iso: 'tg',
  },
  tn: {
    name: 'Тунис',
    code: '216',
    format: '+XXX XXX XXX XXX',
    iso: 'tn',
  },
  ug: {
    name: 'Уганда',
    code: '256',
    format: '+XXX XXX XXX XXX',
    iso: 'ug',
  },
  zm: {
    name: 'Замбия',
    code: '260',
    format: '+XXX XXX XXX XXXX',
    iso: 'zm',
  },
  zw: {
    name: 'Зимбабве',
    code: '263',
    format: '+XXX XXX XXX XXXX',
    iso: 'zw',
  },
  al: {
    name: 'Албания',
    code: '355',
    format: '+XXX XXX XXX XXX',
    iso: 'al',
  },
  ad: {
    name: 'Андорра',
    code: '376',
    format: '+XXX XXX XXX',
    iso: 'ad',
  },
  am: {
    name: 'Армения',
    code: '374',
    format: '+XXX XX XXX XXX',
    iso: 'am',
  },
  by: {
    name: 'Беларусь',
    code: '375',
    format: '+XXX XX XXX XXXX',
    iso: 'by',
  },
  be: {
    name: 'Бельгия',
    code: '32',
    format: '+XX X XXX XX XX',
    iso: 'be',
  },
  ba: {
    name: 'Босния и Герцеговина',
    code: '387',
    format: '+XXX XX XXX XXX',
    iso: 'ba',
  },
  bg: {
    name: 'Болгария',
    code: '359',
    format: '+XXX X XXX XXXX',
    iso: 'bg',
  },
  hr: {
    name: 'Хорватия',
    code: '385',
    format: '+XXX XXX XXX XXX',
    iso: 'hr',
  },
  cy: {
    name: 'Кипр',
    code: '357',
    format: '+XXX XX XXX XXX',
    iso: 'cy',
  },
  ee: {
    name: 'Эстония',
    code: '372',
    format: '+XXX XXX XXX XXX',
    iso: 'ee',
  },
  fi: {
    name: 'Финляндия',
    code: '358',
    format: '+XXX XX XXX XXXX',
    iso: 'fi',
  },
  fr: {
    name: 'Франция',
    code: '33',
    format: '+XX X XX XX XX XX',
    iso: 'fr',
  },
  gi: {
    name: 'Гибралтар',
    code: '350',
    format: '+XXX XXX XXXX',
    iso: 'gi',
  },
  gr: {
    name: 'Греция',
    code: '30',
    format: '+XX X XXX XXXX',
    iso: 'gr',
  },
  hu: {
    name: 'Венгрия',
    code: '36',
    format: '+XX X XXX XXXX',
    iso: 'hu',
  },
  is: {
    name: 'Исландия',
    code: '354',
    format: '+XXX XXX XXXX',
    iso: 'is',
  },
  ie: {
    name: 'Ирландия',
    code: '353',
    format: '+XXX X XXX XXXX',
    iso: 'ie',
  },
  it: {
    name: 'Италия',
    code: '39',
    format: '+XX XXX XXXXXXX',
    iso: 'it',
  },
  xk: {
    name: 'Косово',
    code: '383',
    format: '+XXX XX XXX XXXX',
    iso: 'xk',
  },
  lv: {
    name: 'Латвия',
    code: '371',
    format: '+XXX XX XXX XXXX',
    iso: 'lv',
  },
  lt: {
    name: 'Литва',
    code: '370',
    format: '+XXX XXX XXXXX',
    iso: 'lt',
  },
  lu: {
    name: 'Люксембург',
    code: '352',
    format: '+XXX XX XXX XXX',
    iso: 'lu',
  },
  mk: {
    name: 'Македония',
    code: '389',
    format: '+XXX X XXX XXXX',
    iso: 'mk',
  },
  mt: {
    name: 'Мальта',
    code: '356',
    format: '+XXX XX XXX XXX',
    iso: 'mt',
  },
  md: {
    name: 'Молдова',
    code: '373',
    format: '+XXX XX XXX XXXX',
    iso: 'md',
  },
  mc: {
    name: 'Монако',
    code: '377',
    format: '+XXX XX XX XX XX',
    iso: 'mc',
  },
  me: {
    name: 'Черногория',
    code: '382',
    format: '+XXX XX XXX XXX',
    iso: 'me',
  },
  nl: {
    name: 'Нидерланды',
    code: '31',
    format: '+XX X XXX XXXX',
    iso: 'nl',
  },
  pt: {
    name: 'Португалия',
    code: '351',
    format: '+XXX XXX XXX XXX',
    iso: 'pt',
  },
  sm: {
    name: 'Сан-Марино',
    code: '378',
    format: '+XXX XXX XXXX',
    iso: 'sm',
  },
  rs: {
    name: 'Сербия',
    code: '381',
    format: '+XXX XX XXX XXXX',
    iso: 'rs',
  },
  si: {
    name: 'Словения',
    code: '386',
    format: '+XXX X XXX XXXX',
    iso: 'si',
  },
  es: {
    name: 'Испания',
    code: '34',
    format: '+XX X XXX XXXX',
    iso: 'es',
  },
  ua: {
    name: 'Украина',
    code: '380',
    format: '+XXX XX XXX XXXX',
    iso: 'ua',
  },
  va: {
    name: 'Ватикан',
    code: '39',
    format: '+39 XXX XXX XXX',
    iso: 'va',
  },
  ax: {
    name: 'Аландские острова',
    code: '358',
    format: '+XXX XX XXX XXX',
    iso: 'ax',
  },
  at: {
    name: 'Австрия',
    code: '43',
    format: '+XX XXX XXX XX-XX',
    iso: 'at',
  },
  cz: {
    name: 'Чехия',
    code: '420',
    format: '+XXX XXX XXX XXX',
    iso: 'cz',
  },
  dk: {
    name: 'Дания',
    code: '45',
    format: '+XX XXX XXXX',
    iso: 'dk',
  },
  de: {
    name: 'Германия',
    code: '49',
    format: '+XX XXX XXXXXXX',
    iso: 'de',
  },
  gg: {
    name: 'Гернси',
    code: '44',
    format: '+XX XXXX XXXX',
    iso: 'gg',
  },
  im: {
    name: 'Острова Мэн',
    code: '44',
    format: '+XX XXXX XXXX',
    iso: 'im',
  },
  je: {
    name: 'Джерси',
    code: '44',
    format: '+XX XXXX XXXX',
    iso: 'je',
  },
  li: {
    name: 'Лихтенштейн',
    code: '423',
    format: '+XXX XXX XXX XXX',
    iso: 'li',
  },
  no: {
    name: 'Норвегия',
    code: '47',
    format: '+XX XXX XX XXX',
    iso: 'no',
  },
  pl: {
    name: 'Польша',
    code: '48',
    format: '+XX XXX XXX XXX',
    iso: 'pl',
  },
  ro: {
    name: 'Румыния',
    code: '40',
    format: '+XX XXX XXX XXX',
    iso: 'ro',
  },
  sk: {
    name: 'Словакия',
    code: '421',
    format: '+XXX XXX XXX XXX',
    iso: 'sk',
  },
  sj: {
    name: 'Свалбард и Ян Майен',
    code: '47',
    format: '+XX XXX XX XXX',
    iso: 'sj',
  },
  se: {
    name: 'Швеция',
    code: '46',
    format: '+XX XXX XXX XXX',
    iso: 'se',
  },
  ch: {
    name: 'Швейцария',
    code: '41',
    format: '+XX XXX XXX XXX',
    iso: 'ch',
  },
  gb: {
    name: 'Великобритания',
    code: '44',
    format: '+XX XXXX XXXX',
    iso: 'gb',
  },
  ar: {
    name: 'Аргентина',
    code: '54',
    format: '+XX XXX XXX-XXXX',
    iso: 'ar',
  },
  bz: {
    name: 'Белиз',
    code: '501',
    format: '+XXX XXXX XXXX',
    iso: 'bz',
  },
  bo: {
    name: 'Боливия',
    code: '591',
    format: '+XXX XXX XXXX',
    iso: 'bo',
  },
  br: {
    name: 'Бразилия',
    code: '55',
    format: '+XX XXXXX-XXXX',
    iso: 'br',
  },
  bq: {
    name: 'Карибские Нидерланды',
    code: '599',
    format: '+XXX XXX XXXX',
    iso: 'bq',
  },
  cl: {
    name: 'Чили',
    code: '56',
    format: '+XX XXXX XXXX',
    iso: 'cl',
  },
  co: {
    name: 'Колумбия',
    code: '57',
    format: '+XX XXX XXX XXXX',
    iso: 'co',
  },
  cr: {
    name: 'Коста-Рика',
    code: '506',
    format: '+XXX XXXX XXXX',
    iso: 'cr',
  },
  cu: {
    name: 'Куба',
    code: '53',
    format: '+XX XXXX XXXX',
    iso: 'cu',
  },
  cw: {
    name: 'Кюрасао',
    code: '5999',
    format: '+XXXX XXX XXXX',
    iso: 'cw',
  },
  ec: {
    name: 'Эквадор',
    code: '593',
    format: '+XXX XXXX XXXX',
    iso: 'ec',
  },
  sv: {
    name: 'Сальвадор',
    code: '503',
    format: '+XXX XXXX XXXX',
    iso: 'sv',
  },
  gf: {
    name: 'Французская Гвиана',
    code: '594',
    format: '+XXX XXX XX XX',
    iso: 'gf',
  },
  gp: {
    name: 'Гваделупа',
    code: '590',
    format: '+XXX XXX XX XX',
    iso: 'gp',
  },
  gt: {
    name: 'Гватемала',
    code: '502',
    format: '+XXX XXXX XXXX',
    iso: 'gt',
  },
  gy: {
    name: 'Гайана',
    code: '592',
    format: '+XXX XXX XXXX',
    iso: 'gy',
  },
  ht: {
    name: 'Гаити',
    code: '509',
    format: '+XXX XXXX XXXX',
    iso: 'ht',
  },
  hn: {
    name: 'Гондурас',
    code: '504',
    format: '+XXX XXXX XXXX',
    iso: 'hn',
  },
  mq: {
    name: 'Мартиника',
    code: '596',
    format: '+XXX XXX XX XX',
    iso: 'mq',
  },
  mx: {
    name: 'Мексика',
    code: '52',
    format: '+XX XXXX XXXX',
    iso: 'mx',
  },
  ni: {
    name: 'Никарагуа',
    code: '505',
    format: '+XXX XXXX XXXX',
    iso: 'ni',
  },
  pa: {
    name: 'Панама',
    code: '507',
    format: '+XXX XXXX XXXX',
    iso: 'pa',
  },
  py: {
    name: 'Парагвай',
    code: '595',
    format: '+XXX XXX XXXX',
    iso: 'py',
  },
  pe: {
    name: 'Перу',
    code: '51',
    format: '+XX XXXX XXXX',
    iso: 'pe',
  },
  bl: {
    name: 'Сан-Бертилеми (Карибы)',
    code: '590',
    format: '+XXX XXX XX XX',
    iso: 'bl',
  },
  mf: {
    name: 'Сен-Мартен (владение Франции)',
    code: '590',
    format: '+XXX XXX XX XX',
    iso: 'mf',
  },
  au: {
    name: 'Австралия',
    code: '61',
    format: '+XX XXXX XXXX',
    iso: 'au',
  },
  bn: {
    name: 'Бруней Дарассалам',
    code: '673',
    format: '+XXX XXX XXXX',
    iso: 'bn',
  },
  cx: {
    name: 'Остров Рождества',
    code: '61',
    format: '+XX XXXX XXXX',
    iso: 'cx',
  },
  cc: {
    name: 'Кокосовые (Килинг) острова',
    code: '61',
    format: '+XX XXXX XXXX',
    iso: 'cc',
  },
  ck: {
    name: 'Острова Кука',
    code: '682',
    format: '+XXX XX XXX',
    iso: 'ck',
  },
  fj: {
    name: 'Фиджи',
    code: '679',
    format: '+XXX XXX XXXX',
    iso: 'fj',
  },
  pf: {
    name: 'Французская Полинезия',
    code: '689',
    format: '+XXX XX XX XX',
    iso: 'pf',
  },
  id: {
    name: 'Индонезия',
    code: '62',
    format: '+XX XXX XXXX XXX',
    iso: 'id',
  },
  ki: {
    name: 'Кирибати',
    code: '686',
    format: '+XXX XXXX XXXX',
    iso: 'ki',
  },
  my: {
    name: 'Малайзия',
    code: '60',
    format: '+XX XXX XXX XXX',
    iso: 'my',
  },
  mh: {
    name: 'Маршалловы Острова',
    code: '692',
    format: '+XXX XXX XXXX',
    iso: 'mh',
  },
  fm: {
    name: 'Микронезия',
    code: '691',
    format: '+XXX XXX XXXX',
    iso: 'fm',
  },
  nr: {
    name: 'Науру',
    code: '674',
    format: '+XXX XXXX',
    iso: 'nr',
  },
  nc: {
    name: 'Новая Каледония',
    code: '687',
    format: '+XXX XX XX XX',
    iso: 'nc',
  },
  nz: {
    name: 'Новая Зеландия',
    code: '64',
    format: '+XX XXX XXX XXXX',
    iso: 'nz',
  },
  nu: {
    name: 'Ниуэ',
    code: '683',
    format: '+XXX XXXX',
    iso: 'nu',
  },
  nf: {
    name: 'Норфолк',
    code: '672',
    format: '+XXX XXX XXX',
    iso: 'nf',
  },
  pw: {
    name: 'Палау',
    code: '680',
    format: '+XXX XXX XXXX',
    iso: 'pw',
  },
  pg: {
    name: 'Папуа-Новая Гвинея',
    code: '675',
    format: '+XXX XXX XXXX',
    iso: 'pg',
  },
  ph: {
    name: 'Филиппины',
    code: '63',
    format: '+XX XXXX XXXX',
    iso: 'ph',
  },
  sg: {
    name: 'Сингапур',
    code: '65',
    format: '+XX XXXX XXXX',
    iso: 'sg',
  },
  sb: {
    name: 'Соломоновы острова',
    code: '677',
    format: '+XXX XXXXX',
    iso: 'sb',
  },
  th: {
    name: 'Таиланд',
    code: '66',
    format: '+XX XXXX XXXX',
    iso: 'th',
  },
  tl: {
    name: 'Восточный Тимор',
    code: '670',
    format: '+XXX XXX XXXX',
    iso: 'tl',
  },
  tk: {
    name: 'Острова Токелау',
    code: '690',
    format: '+XXX XXXX',
    iso: 'tk',
  },
  to: {
    name: 'Тонга',
    code: '676',
    format: '+XXX XXXXX',
    iso: 'to',
  },
  tv: {
    name: 'Тувалу',
    code: '688',
    format: '+XXX XXXX',
    iso: 'tv',
  },
  vu: {
    name: 'Вануату',
    code: '678',
    format: '+XXX XXXXX',
    iso: 'vu',
  },
  wf: {
    name: 'Уоллис и Футуна',
    code: '681',
    format: '+XXX XX XX XX',
    iso: 'wf',
  },
  bd: {
    name: 'Бангладеш',
    code: '880',
    format: '+XXX XXXXX XXXXX',
    iso: 'bd',
  },
  kh: {
    name: 'Камбоджа',
    code: '855',
    format: '+XXX XXX XXX XXX',
    iso: 'kh',
  },
  cn: {
    name: 'Китай',
    code: '86',
    format: '+XX XXX XXXX XXXX',
    iso: 'cn',
  },
  hk: {
    name: 'Гонконг',
    code: '852',
    format: '+XXX XXXX XXXX',
    iso: 'hk',
  },
  jp: {
    name: 'Япония',
    code: '81',
    format: '+XX XXXX XXXX',
    iso: 'jp',
  },
  la: {
    name: 'Лаос',
    code: '856',
    format: '+XXX XX XXX XXX',
    iso: 'la',
  },
  mo: {
    name: 'Макао',
    code: '853',
    format: '+XXX XXXX XXXX',
    iso: 'mo',
  },
  kp: {
    name: 'Северная Корея',
    code: '850',
    format: '+XXX XXXX XXXX',
    iso: 'kp',
  },
  kr: {
    name: 'Южная Корея',
    code: '82',
    format: '+XX XXX XXXX XXXX',
    iso: 'kr',
  },
  tw: {
    name: 'Тайвань',
    code: '886',
    format: '+XXX XXX XXX XXX',
    iso: 'tw',
  },
  vn: {
    name: 'Вьетнам',
    code: '84',
    format: '+XX XXX XXX XXXX',
    iso: 'vn',
  },
  af: {
    name: 'Афганистан',
    code: '93',
    format: '+XX XXX XXX XXXX',
    iso: 'af',
  },
  az: {
    name: 'Азербайджан',
    code: '994',
    format: '+XXX XX XXX XX XX',
    iso: 'az',
  },
  bh: {
    name: 'Бахрейн',
    code: '973',
    format: '+XXX XXXX XXXX',
    iso: 'bh',
  },
  bt: {
    name: 'Бутан',
    code: '975',
    format: '+XXX XX XXX XXX',
    iso: 'bt',
  },
  ge: {
    name: 'Грузия',
    code: '995',
    format: '+XXX XXX XX XX XX',
    iso: 'ge',
  },
  in: {
    name: 'Индия',
    code: '91',
    format: '+XX XXXXX XXXXX',
    iso: 'in',
  },
  ir: {
    name: 'Иран',
    code: '98',
    format: '+XX XXX XXX XXXX',
    iso: 'ir',
  },
  iq: {
    name: 'Ирак',
    code: '964',
    format: '+XXX XXX XXX XXXX',
    iso: 'iq',
  },
  il: {
    name: 'Израиль',
    code: '972',
    format: '+XXX XX XXX XXXX',
    iso: 'il',
  },
  jo: {
    name: 'Иордания',
    code: '962',
    format: '+XXX X XXXX XXXX',
    iso: 'jo',
  },
  kw: {
    name: 'Кувейт',
    code: '965',
    format: '+XXX XXXX XXXX',
    iso: 'kw',
  },
  kg: {
    name: 'Киргизстан',
    code: '996',
    format: '+XXX XXX XXX XXX',
    iso: 'kg',
  },
  lb: {
    name: 'Ливан',
    code: '961',
    format: '+XXX X XXX XXXX',
    iso: 'lb',
  },
  mv: {
    name: 'Мальдивы',
    code: '960',
    format: '+XXX XXX XXXX',
    iso: 'mv',
  },
  mn: {
    name: 'Монголия',
    code: '976',
    format: '+XXX XX XX XXXX',
    iso: 'mn',
  },
  mm: {
    name: 'Мьянма',
    code: '95',
    format: '+XX XXX XXX XXX',
    iso: 'mm',
  },
  np: {
    name: 'Непал',
    code: '977',
    format: '+XXX XX XXX XXX',
    iso: 'np',
  },
  om: {
    name: 'Оман',
    code: '968',
    format: '+XXX XXXX XXXX',
    iso: 'om',
  },
  pk: {
    name: 'Пакистан',
    code: '92',
    format: '+XX XXX XXXXXXX',
    iso: 'pk',
  },
  ps: {
    name: 'Палестинская автономия',
    code: '970',
    format: '+XXX XXX XXX XXXX',
    iso: 'ps',
  },
  qa: {
    name: 'Катар',
    code: '974',
    format: '+XXX XXXX XXXX',
    iso: 'qa',
  },
  sa: {
    name: 'Саудовская Аравия',
    code: '966',
    format: '+XXX X XXXX XXXX',
    iso: 'sa',
  },
  lk: {
    name: 'Шри-Ланка',
    code: '94',
    format: '+XX XXX XXX XXXX',
    iso: 'lk',
  },
  sy: {
    name: 'Сирия',
    code: '963',
    format: '+XXX XX XXX XXXX',
    iso: 'sy',
  },
  tj: {
    name: 'Таджикистан',
    code: '992',
    format: '+XXX XXX XX XX XX',
    iso: 'tj',
  },
  tr: {
    name: 'Турция',
    code: '90',
    format: '+XX XXX XXX XXXX',
    iso: 'tr',
  },
  tm: {
    name: 'Туркменистан',
    code: '993',
    format: '+XXX X XXXXXXX',
    iso: 'tm',
  },
  ae: {
    name: 'Объединённые Арабские Эмираты',
    code: '971',
    format: '+XXX XX XXX XXXX',
    iso: 'ae',
  },
  uz: {
    name: 'Узбекистан',
    code: '998',
    format: '+XXX XX XXX XXXX',
    iso: 'uz',
  },
  ye: {
    name: 'Йемен',
    code: '967',
    format: '+XXX XXX XXX XXX',
    iso: 'ye',
  },
}

export default countries
